config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root 'users#index'
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy]
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      member do
        post 'like'
        delete 'unlike'
      end
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, User
    can :read, Post
    can :read, Comment
    can :manage, Post, author: user
    can :manage, Comment, author: user
    can :manage, Post if user.is? :admin
    can :manage, Comment if user.is? :admin
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  before_save :update_comments_counter
  after_destroy :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  before_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_save :update_posts_counter
  after_destroy :update_posts_counter

  before_validation :set_counter_to_zero

  def excerpt
    return text unless text.length > 50

    "#{text.slice(0, 50)} ..."
  end

  def set_counter_to_zero
    self.comments_counter = 0 if comments_counter.nil?
    self.likes_counter = 0 if likes_counter.nil?
  end

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def five_recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :role, inclusion: { in: %w[admin user], message: '%<value>s is not a valid role [admin, user]' }

  before_validation :set_counter_to_zero

  def is?(requested_role)
    role == requested_role.to_s
  end

  def set_counter_to_zero
    self.posts_counter = 0 if posts_counter.nil?
  end

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::API
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::ApiController
  before_action :find_user_post

  def index
    @comments = @post.comments

    render json: @comments, include: ['author']
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.author = @user

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { error: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_user_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::ApiController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts

    render json: @posts, include: %w[author comments]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?
  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  before_action :find_user_post

  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.new(comment_params)
    comment.post = @post
    comment.author = current_user

    if comment.save
      flash[:success] = 'Comment saved successfully'
      redirect_to user_post_path(user_id: @user.id, id: @post.id)
    else
      flash.now[:error] = 'error: comment could not be saved'
      redirect_to new_user_post_comment_path(user_id: @user.id, post_id: @post.id)
    end
  end

  def destroy
    @post.comments.destroy(params[:id])
    redirect_to user_post_path(user_id: @user.id, id: @post.id)
  end

  private

  def find_user_post
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  before_action :find_user_post, only: %i[show like]

  def index
    page = params[:page] || 1
    per_page = 10

    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author)
      .includes(:comments)
      .order(created_at: :asc)
      .offset((page.to_i - 1) * per_page)
      .limit(per_page)

    @total_pages = (Post.count.to_f / per_page).ceil
    @author = @posts.first.author unless @posts.first.nil?
  end

  def show
    @current_user = current_user
    @like = Like.new
  end

  def new
    @post = Post.new
    @current_user = current_user
  end

  def create
    post = Post.new(post_params)
    post.author = current_user
    post.comments_counter = 0
    post.likes_counter = 0

    if post.save
      flash[:success] = 'post saved successfully'
      redirect_to '/'
    else
      flash.now[:error] = 'error: question could not be saved'
      redirect_to new_user_post_path
    end
  end

  def destroy
    @current_user = current_user
    @current_user.posts.destroy(params[:id])
    redirect_to user_path(id: @current_user.id)
  end

  def like
    like = Like.new
    like.post = @post
    like.author = current_user

    if like.save
      flash[:success] = 'Like saved successfully'
    else
      flash[:error] = 'Error: Like could not be saved'
    end

    redirect_to user_post_path(user_id: @user.id, id: @post.id)
  end

  private

  def find_user_post
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.three_recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/comments_helper_spec.rb
require 'rails_helper'

# Specs in this file have access to a helper object that includes
# the CommentsHelper. For example:
#
# describe CommentsHelper do
#   describe "string concat" do
#     it "concats two strings with spaces" do
#       expect(helper.concat_strings("this","that")).to eq("this that")
#     end
#   end
# end
RSpec.describe CommentsHelper, type: :helper do
  pending "add some examples to (or delete) #{__FILE__}"
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/new.html.erb
<div class="container mt-5">
  <h1>Add New Comment to post: <%= @post.title %></h1>
  <% if @comment.errors.any? %>
    <div class="post-errors-box">
      <p><%= pluralize(@comment.errors.count, "error") %> found:</p>

      <ul class="post-errors-ul">
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: @comment, url: user_post_comments_path(user_id: @user.id, post_id: @post.id) do |form| %>
    <div class="form-group">
      <%= form.label :text %>
      <%= form.text_area :text, size: "70x5", class: 'form-control' %>
    </div>
    <%= form.submit class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" />
  </head>

  <body>
    <header class="p-3 text-bg-dark">
      <div class="container">
        <div class="d-flex w-100 flex-wrap align-items-center justify-content-end">
          <% if user_signed_in? %>
            <div class="text-end">
              <%= link_to 'Logout', destroy_user_session_path, class: "btn btn-warning", data: { turbo_method: :delete } %>
            </div>
          <% else %>
            <div class="text-end">
              <%= link_to 'Login', new_user_session_path, class: "btn btn-outline-light me-2" %>
              <%= link_to 'Sign-up', new_user_registration_path, class: "btn btn-warning" %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <div class="container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</html>

app/views/posts/index.html.erb
<div class="container mt-5">
<%= render 'shared/user_card', user: @author unless @author.nil? %>
  <% if @posts.empty? %>
    <p>This user has no posts yet</p>
    <%= link_to 'Back to users', '/users', class: 'btn btn-info' %>
  <% end %>
  <% @posts.each do |post| %>
    <a href="/users/<%= post.author.id %>/posts/<%= post.id %>" class="text-decoration-none">
      <div class="mb-4">
        <%= render 'shared/post_card', post: post %>
        <%= render 'shared/comments_card', comments: post.five_recent_comments unless post.five_recent_comments.empty? %>
      </div>
    </a>
  <% end %>
  <nav aria-label="Pagination for posts" class="mt-5">
    <ul class="pagination justify-content-center">
      <% (1..@total_pages).each do |page| %>
        <li class="page-item"><a class="page-link" href="<%= user_posts_path(user_id: @author.id) + "?page=#{page}" %>"><%= page %></a></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
  <h1>Add New Post</h1>
  <% if @post.errors.any? %>
    <div class="post-errors-box">
      <p><%= pluralize(@post.errors.count, "error") %> found:</p>

      <ul class="post-errors-ul">
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with url: "/users/#{@current_user.id}/posts", model: @post do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :text %>
      <%= form.text_area :text, size: "70x5", class: 'form-control' %>
    </div>
    <%= form.submit class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <div class="d-flex justify-content-between gap-1">
        <h4 class="card-title"><%= @post.title %> by <%= @post.author.name %></h4>
        <div class="d-flex gap-1">
          <p class="m-0">Comments: <%= @post.comments_counter %>,</p>
          <p class="m-0">Likes: <%= @post.likes_counter %></p>
        </div>
      </div>
      <p class="mt-2"><%= @post.text %></p>
    </div>
    <% unless @current_user.nil? %>
      <div class="card-footer d-flex justify-content-between">
        <%= render 'shared/like' %>
        <%= link_to 'Delete Post', "/users/#{@current_user.id}/posts/#{@post.id}", class: 'btn btn-danger', data: { turbo_method: :delete } if can? :destroy, @post %>
      </div>
    <% end %>
  </div>
  <%= render 'shared/comments_card', comments: @post.comments unless @post.comments.empty? %>
  <% unless @current_user.nil? %>
    <%= link_to 'Add a new comment', "/users/#{@current_user.id}/posts/#{@post.id}/comments/new", class: "btn btn-primary mt-3" %>
  <% end %>
</div>

app/views/shared/_comments_card.html.erb
<div class="card">
  <div class="card-body">
    <% comments.each do |comment| %>
      <div class="d-flex justify-content-between w-100 border-bottom py-3 align-items-center">
        <p class="m-0"><b><%= comment.author.name %></b>: <%= comment.text %></p>
        <% unless @user.nil? || @post.nil? %>
          <%= link_to 'Delete', user_post_comment_path(user_id: @user.id, post_id: @post.id, id: comment.id), class: 'btn btn-danger', data: { turbo_method: :delete } if can? :destroy, comment %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_like.html.erb
<%= form_with url: like_user_post_path(user_id: @current_user.id, id: @post.id), model: @like do |form| %>
    <%= form.submit "Like", class: 'btn btn-primary' %>
  <% end %>

app/views/shared/_post_card.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title"><%= post.title %></h4>
    <div class="text-truncate text-justify"><%= post.excerpt %></div>
    <div class="d-flex justify-content-end gap-1 align-items-end">
      <p class="m-0">Comments: <%= post.comments_counter %>,</p>
      <p class="m-0">Likes: <%= post.likes_counter %></p>
    </div>
  </div>
</div>

app/views/shared/_user_card.html.erb
<div class="card mb-3">
  <div class="d-flex">
    <img src="<%= user.photo %>" alt="avatar" />
    <div class="card-body">
      <div class="card-title">
        <h3 class="m-0"><b><%= user.email %></b></h3>
        <h5 class="m-0"><b><%= user.role %></b></h5>
      </div>
      <div class="d-flex h-50 justify-content-end align-items-end">
        <p class="m-0">Number of posts: <%= user.posts_counter %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-5">
  <% if @users.empty? %>
    <p>There are no users for now</p>
  <% end %>
  <% @users.each do |user| %>
    <a href="/users/<%= user.id %>" class="text-decoration-none">
      <%= render 'shared/user_card', user: user %>
    </a>
  <% end %>
  <% if @current_user %>
  <%= link_to 'Add a new post', new_user_post_path(user_id: @current_user.id), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <%= render 'shared/user_card', user: @user %>
  <div class="card mb-4">
    <div class="card-body">
      <h4 class="card-title">Bio</h4>
      <p><%= @user.bio %></p>
    </div>
  </div>
  <% @posts.each do |post| %>
    <a href="<%= user_post_path(user_id: @user.id, id: post.id) %>" class="text-decoration-none">
      <div class="mb-3">
        <%= render 'shared/post_card', post: post %>
      </div>
    </a>
  <% end %>
  <div class="w-100 mt-5 d-flex justify-content-center align-items-center">
    <a href="/users/<%= @user.id %>/posts" class="btn btn-primary">See all posts</a>
  </div>
</div>